describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://itera-qa.azurewebsites.net/')
    cy.wait(2)
    cy.get('.form-inline > .navbar-nav > :nth-child(2) > .nav-link').click()
    cy.get('#Username').type('chester13')
    cy.wait(1)
    cy.get('#Password').type('chester13')
    cy.wait(1)
    cy.get('.btn-primary').click()
    cy.wait(1)
    cy.get(':nth-child(4) > .btn').click()
    cy.wait(1)
    cy.get('#Name').should('have.value', '')
    cy.wait(1)
    cy.get('#Company').type('vn.co')
    cy.wait(1)
    cy.get('#Address').type('Cijulang')
    cy.wait(1)
    cy.get('#City').type('Pangandaran')
    cy.wait(1)
    cy.get('#Phone').type('02650987')
    cy.wait(1)
    cy.get('#Email').should('have.value', '')
    cy.wait(1)
    cy.get('.col-md-offset-2 > .btn').click()
    cy.wait(1)
    cy.get('.col-md-offset-2 > .btn')
  
    })
      }) 
      Cypress.on('uncaught:exception', (err, runnable) => {  
      return false
  })